public class testingInteger {

   public static integer c = 10;

   integer b = 25;
    @testvisible
    private void testingInteger3(){
     system.debug('value of c' + c);
        system.debug('value of b' + b);
     c = 15;
     b = 20;
    }
    
    public void testingInteger2(){
        system.debug('value of c' + c);
        system.debug('value of b' + b);
       // return b;
      //  system.debug('value of c' + c);
    }
    
    
    
    
  
}